config/routes.rb
Rails.application.routes.draw do
  get 'klients/new'
  get 'uchet/main'
  get "users/privilege"
  resources :klients
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'users/new'
  match '/signup',   to: 'users#new',                   via: 'get'
  match '/signin',   to: 'sessions#new',                via: 'get'
  match '/signout',  to: 'sessions#destroy',            via: 'delete'

  root 'uchet#main'

end

app/models/acsesorie.rb
class Acsesorie < ActiveRecord::Base
end

app/models/cartrige.rb
class Cartrige < ActiveRecord::Base
end

app/models/firm.rb
class Firm < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/klient.rb
class Klient < ActiveRecord::Base
  validates :fio, presence: true
  validates :tel, presence: true
end

app/models/priem.rb
class Priem < ActiveRecord::Base
end

app/models/tovar.rb
class Tovar < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: {maximum: 100, too_long: " має бути не довше 100 символів  "}
  has_secure_password
  validates :password, length:  {:minimum => 6,
                                 :too_short => " має бути не менше 6 символів"}
  before_create :create_remember_token
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  private
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/klients_controller.rb
class KlientsController < ApplicationController
  def new
    @klient=Klient.new
  end
  def create
    @klient=Klient.new(klient_params)
    if @klient.save
      flash[:success] =  "Клієнт збережений"
      redirect_to @klient
    else
      render "klients/new"
    end
  end
  def show
    @klient=Klient.all
  end
  private

    def klient_params
      params.require(:klient).permit(:fio, :tel, :ikod)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(name: params[:session][:name].downcase )
    if user&&user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Неправильний логін чи пароль' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/uchet_controller.rb
class UchetController < ApplicationController
  def main
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user=User.new
  end
  def show
    @user=User.find(params[:id])
  end

  def create
    @user=User.new(user_params)
    if @user.save
      sign_in(@user)
      flash[:success] =  "Реєстрація успішна"
      redirect_to @user
    else
      render "users/new"
    end
  end
  def privilege
    @users=User.all
  end
  def update
    @user=User.find_by id: params[:id]
    if params[:update]
      @user.update_attribute(:privilege, params[:user][:privilege])
      redirect_to users_privilege_path
    else
      @user.delete
      redirect_to users_privilege_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :name, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/klients_helper.rb
module KlientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end
  def user_privilege?
      @current_user.privilege
  end
  def current_user=(user)
    @current_user = user
  end
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  def signed_in?
    !current_user.nil?
  end
  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/uchet_helper.rb
module UchetHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/klients/new.html.erb
<h1>Новий клієнт</h1>
<div class="row">
  <div class="col-sm-4">.col-sm-4</div>
  <div class="col-sm-4">.col-sm-4</div>
  <div class="col-sm-4">.col-sm-4</div>
</div>
    <%= form_for (@klient) do |f| %>
        <%= render 'shared/error_messages_klients' %>
      <div class="row">
        <div class="col-sm-4">ПІБ
        <%=f.text_field :fio %></div>
        <div class="col-sm-4">№ телефона:
        <%=f.telephone_field :tel%></div>
        <div class="col-sm-4">Ідентифікаційний код:
        <%=f.number_field :ikod, in: 1000000000..9999999999%></div>
      </div>
        <%= f.submit "Підтвердити", class: "btn btn-large btn-primary" %>
    <%end%>

app/views/klients/show.html.erb
<% @klient.each do |kl|%>
    <%= form_for (kl) do |f|%>
        <%=f.label :ПІБ%>
        <%=f.text_field :fio, :value => kl.fio%><br>
        <%= f.submit "Змінити", class: "btn btn-small btn-primary" %>
    <%end%>
<%end%>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav navbar-nav pull-right">

          <% if signed_in? %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Продажі <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <% if user_privilege?%>
                      <li><%= link_to "Дозволи", "#" %></li>
                  <%end%>
                </ul>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Переустановки <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <% if user_privilege?%>
                      <li><%= link_to "Дозволи", "#" %></li>
                  <%end%>
                </ul>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Картриджі <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <% if user_privilege?%>
                      <li><%= link_to "Дозволи", "#" %></li>
                  <%end%>
                </ul>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Переустановки <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <% if user_privilege?%>
                      <li><%= link_to "Дозволи", "#" %></li>
                  <%end%>
                </ul>

              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Клієнти <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <% if user_privilege?%>
                      <li><%= link_to "Новий клієнт", klients_new_path %></li>
                  <%end%>
                </ul>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Аккаунт <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Профіль", current_user %></li>
                  <% if user_privilege?%>
                      <li><%= link_to "Дозволи", users_privilege_path %></li>
                  <%end%>
                  <li><%= link_to "Властивості", '#' %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Вийти", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Ввійти", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uchet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= yield %>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_error_messages_klients.html.erb
<% if @klient.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@klient.errors.count, "error") %>.
      </div>
      <ul>
        <% @klient.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/uchet/main.html.erb
<div class="center hero-unit">
  <h1>Uchet#main</h1>
<p>Find me in app/views/uchet/main.html.erb</p>
</div>

app/views/users/new.html.erb
<% provide(:title, "Реєстрація") %>
   <h1> Реєстрація </h1>
<%= form_for (@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :"Ім'я" %>
    <%= f.text_field :name %>
    <%= f.label :Пароль%>
    <%= f.password_field :password %>
    <%= f.label :Підтвердження %>
    <%= f.password_field :password_confirmation %><br>
    <%= f.submit "Створити користувача", class: "btn btn-large btn-primary" %>
<%end%>

app/views/users/privilege.html.erb
<% @users.each do |user| %>
    <%= form_for (user) do |f| %>
        <%= f.label user.name%>
        <%= f.check_box :privilege%>
        <%= f.submit "Обновити", name: "update", class: "btn btn-sm btn-primary" %>
        <%= f.submit "Видалити", name: "delete", class: "btn btn-sm btn-primary" %>
    <%end%>
<%end%>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %>
        <%= @user.password %>
      </h1>
    </section>
  </aside>
</div>